[Interface]
Address = 10.8.0.2/24
PrivateKey = QCp6pDvinYnTgiIJmk5jAeT9CHY0iXFUAJb9Uq+Z/kE=

[Peer]
PublicKey = 0O7vnDxZ36+1YCgrtx3wya3I2MLg/jTNeb0ZLBxFZxY=
Endpoint = vasilyev.tech:8443
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
